GET http://localhost:3001/api/1/users HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhlbmNvaGVuODNAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjY5NDYyNzUzLCJleHAiOjE2NzIwNTQ3NTN9.0LlJZza312xQq_Pr-DXw0kKdmccHUgp8S75banxgDaE
