DELETE http://localhost:3040/1/users/638180ab8ade5ab20b71b384 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhlbmNvaGVuODNAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjY5NDI3MzI5LCJleHAiOjE2NzIwMTkzMjl9.bYvF4LGfImH5uvlrtureVKfZPYetPFD9J69AUaL0SPc
